-- Ministerio Gosen - PostgreSQL base migration
-- Converts core SQL Server schema/data and adds role Miembro + automatic role synchronization.

BEGIN;

DROP TABLE IF EXISTS actividad_usuario CASCADE;
DROP TABLE IF EXISTS actividades_ministerio CASCADE;
DROP TABLE IF EXISTS usuarios_ministerio CASCADE;
DROP TABLE IF EXISTS citas CASCADE;
DROP TABLE IF EXISTS error CASCADE;
DROP TABLE IF EXISTS chat_bot_opciones CASCADE;
DROP TABLE IF EXISTS actividad CASCADE;
DROP TABLE IF EXISTS tipo_actividad CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS ministerio CASCADE;
DROP TABLE IF EXISTS rol CASCADE;
DROP TABLE IF EXISTS campana  CASCADE;
DROP TABLE IF EXISTS campana_destinatario CASCADE;
DROP TABLE IF EXISTS campana_envio_log CASCADE;

CREATE TABLE rol (
    id_rol integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion varchar(20) NOT NULL UNIQUE,
    CONSTRAINT chk_descripcion_rol CHECK (descripcion IN ('Admin','Usuario','Miembro'))
);

CREATE TABLE ministerio (
    id_ministerio integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion_ministerio varchar(100) NOT NULL,
    observaciones_ministerio varchar(200)
);

CREATE TABLE tipo_actividad (
    id_tipo_actividad integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tipo varchar(50) NOT NULL
);

CREATE TABLE usuario (
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificacion varchar(20) NOT NULL UNIQUE,
    nombre varchar(100) NOT NULL,
    correo varchar(100) NOT NULL UNIQUE,
    contrasena varchar(255) NOT NULL,
    estado char(1) NOT NULL,
    id_rol integer NOT NULL,
    usa_contrasena_temp boolean NOT NULL DEFAULT false,
    CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES rol(id_rol),
    CONSTRAINT chk_estado_usuario CHECK (estado IN ('A','I'))
);

CREATE TABLE actividad (
    id_actividad integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_actividad varchar(100) NOT NULL,
    fecha_ini date NOT NULL,
    fecha_fin date,
    lugar varchar(100),
    hora_ini time,
    hora_fin time,
    id_tipo_actividad integer NOT NULL,
    CONSTRAINT fk_actividad_tipo_act FOREIGN KEY (id_tipo_actividad)
        REFERENCES tipo_actividad(id_tipo_actividad)
);

CREATE TABLE actividad_usuario (
    id_actividad_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_actividad integer NOT NULL,
    id_usuario integer NOT NULL,
    fecha date NOT NULL,
    hora time,
    CONSTRAINT fk_activ_usuario_activ FOREIGN KEY (id_actividad)
        REFERENCES actividad(id_actividad),
    CONSTRAINT fk_activ_usuario_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);

CREATE TABLE actividades_ministerio (
    id_minis_actividad integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_actividad integer NOT NULL,
    id_ministerio integer NOT NULL,
    fecha date,
    observacion varchar(200),
    CONSTRAINT fk_activ_min_activ FOREIGN KEY (id_actividad)
        REFERENCES actividad(id_actividad),
    CONSTRAINT fk_activ_min_minist FOREIGN KEY (id_ministerio)
        REFERENCES ministerio(id_ministerio)
);

CREATE TABLE chat_bot_opciones (
    id_opcion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto_opcion varchar(200) NOT NULL,
    respuesta varchar(200),
    id_opcion_padre integer,
    orden integer NOT NULL DEFAULT 1,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT fk_opcion_padre FOREIGN KEY (id_opcion_padre)
        REFERENCES chat_bot_opciones(id_opcion)
);

CREATE TABLE citas (
    id_cita integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_cita date NOT NULL,
    hora_cita time(0) NOT NULL,
    id_usuario_cita integer NOT NULL,
    id_usuario_encargado integer NOT NULL,
    observacion_inicial varchar(200),
    detalle_cita varchar(500),
    estado varchar(20) NOT NULL DEFAULT 'Pendiente',
    CONSTRAINT fk_cita_usuario FOREIGN KEY (id_usuario_cita)
        REFERENCES usuario(id_usuario),
    CONSTRAINT fk_cita_encargado FOREIGN KEY (id_usuario_encargado)
        REFERENCES usuario(id_usuario),
    CONSTRAINT chk_estado_cita CHECK (estado IN ('Pendiente','Atendida')),
    CONSTRAINT chk_horario_cita CHECK (hora_cita >= TIME '08:00:00' AND hora_cita <= TIME '17:00:00')
);

CREATE TABLE error (
    consecutivo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje text NOT NULL,
    lugar varchar(50) NOT NULL,
    fechahora timestamp NOT NULL,
    id_usuario integer NOT NULL
);

CREATE TABLE usuarios_ministerio (
    id_usuario_ministerio integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ministerio integer NOT NULL,
    id_usuario integer NOT NULL,
    fecha_ingreso date,
    fecha_salida date,
    estado varchar(20),
    observacion varchar(200),
    CONSTRAINT fk_usuario_min_minist FOREIGN KEY (id_ministerio)
        REFERENCES ministerio(id_ministerio),
    CONSTRAINT fk_usuario_min_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);

CREATE TABLE campana (
    id_campana integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    titulo varchar(150) NOT NULL,
    asunto varchar(200) NOT NULL,
    contenido text NOT NULL,

    plantilla varchar(30) NOT NULL DEFAULT 'General',

    estado varchar(20) NOT NULL DEFAULT 'Borrador',

    fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_envio timestamp NULL,

    id_usuario_creador integer NOT NULL,

    CONSTRAINT fk_campana_usuario
        FOREIGN KEY (id_usuario_creador)
        REFERENCES usuario(id_usuario),

    CONSTRAINT chk_estado_campana
        CHECK (estado IN (
            'Borrador',
            'Procesando',
            'Enviada',
            'Parcial',
            'Error'
        ))
);

CREATE TABLE campana_destinatario (
    id_campana_destinatario bigint
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_campana integer NOT NULL,
    id_usuario integer NULL,

    nombre_destinatario varchar(100) NOT NULL,
    correo_destinatario varchar(100) NOT NULL,

    estado_envio varchar(20) NOT NULL DEFAULT 'Pendiente',

    fecha_envio timestamp NULL,

    detalle_error text NULL,

    CONSTRAINT fk_campana_dest_campana
        FOREIGN KEY (id_campana)
        REFERENCES campana(id_campana),

    CONSTRAINT fk_campana_dest_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario),

    CONSTRAINT chk_estado_envio_campana
        CHECK (estado_envio IN (
            'Pendiente',
            'Enviado',
            'Error'
        )),

    CONSTRAINT uq_campana_correo
        UNIQUE (id_campana, correo_destinatario)
);

CREATE TABLE campana_envio_log (
    id_log bigint
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_campana integer NOT NULL,
    id_usuario integer NULL,

    nombre_destinatario varchar(100),
    correo_destinatario varchar(100) NOT NULL,

    asunto varchar(200) NOT NULL,
    contenido text NOT NULL,

    estado varchar(20) NOT NULL,

    fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

    detalle_error text NULL,

    CONSTRAINT fk_log_campana
        FOREIGN KEY (id_campana)
        REFERENCES campana(id_campana)
);

-- Initial data from SQL Server script
INSERT INTO rol (id_rol, descripcion) VALUES
(1, 'Admin'),
(2, 'Usuario'),
(3, 'Miembro');

INSERT INTO ministerio (id_ministerio, descripcion_ministerio, observaciones_ministerio) VALUES
(1, 'Ministerio de Jóvenes', 'Ministerio encargado de actividades juveniles'),
(2, 'Ministerio de Música', 'Ministerio encargado de la alabanza y música');

INSERT INTO tipo_actividad (id_tipo_actividad, nombre_tipo) VALUES
(1, 'Culto'),
(2, 'Reunión');

INSERT INTO usuario (id_usuario, identificacion, nombre, correo, contrasena, estado, id_rol, usa_contrasena_temp) VALUES
(1, '000000000', 'ADMINISTRADOR GOSÉN', 'ministeriogosen@gmail.com', '$2a$11$5/R6N6tBQwXQaH9lolcgUe2c2uqOB6ri6jzD1cGjABlY37R5JfXzG', 'A', 1, false),
(2, '116700557', 'FERNANDA FAJARDO TORRES', 'mfajardo00557@ufide.ac.cr', '$2a$11$LTs1pJBrO6sBEMlnqDSFleNkTdrnah/e6GLsPL4JphVnZpiETHl6K', 'A', 2, false);

INSERT INTO actividad (id_actividad, nombre_actividad, fecha_ini, fecha_fin, lugar, hora_ini, hora_fin, id_tipo_actividad) VALUES
(1, 'Culto Juvenil', DATE '2026-07-28', DATE '2026-08-07', 'Salón principal', TIME '18:00:00', TIME '20:00:00', 1),
(2, 'Reunión de Jóvenes', DATE '2026-07-28', DATE '2026-08-07', 'Aula 1', TIME '16:00:00', TIME '18:00:00', 2),
(3, 'Culto de Alabanza', DATE '2026-07-28', DATE '2026-08-07', 'Templo principal', TIME '09:00:00', TIME '11:00:00', 1),
(4, 'Ensayo Musical', DATE '2026-07-28', DATE '2026-08-07', 'Salón de música', TIME '19:00:00', TIME '21:00:00', 2);

INSERT INTO actividades_ministerio (id_minis_actividad, id_actividad, id_ministerio, fecha, observacion) VALUES
(1, 1, 1, DATE '2026-07-28', 'Actividad del Ministerio de Jóvenes'),
(2, 2, 1, DATE '2026-07-28', 'Reunión de planificación juvenil'),
(3, 3, 2, DATE '2026-07-28', 'Actividad del Ministerio de Música'),
(4, 4, 2, DATE '2026-07-28', 'Ensayo general del equipo de música');

-- Advance identity sequences after inserting explicit IDs.
SELECT setval(pg_get_serial_sequence('rol','id_rol'), (SELECT max(id_rol) FROM rol));
SELECT setval(pg_get_serial_sequence('ministerio','id_ministerio'), (SELECT max(id_ministerio) FROM ministerio));
SELECT setval(pg_get_serial_sequence('tipo_actividad','id_tipo_actividad'), (SELECT max(id_tipo_actividad) FROM tipo_actividad));
SELECT setval(pg_get_serial_sequence('usuario','id_usuario'), (SELECT max(id_usuario) FROM usuario));
SELECT setval(pg_get_serial_sequence('actividad','id_actividad'), (SELECT max(id_actividad) FROM actividad));
SELECT setval(pg_get_serial_sequence('actividades_ministerio','id_minis_actividad'), (SELECT max(id_minis_actividad) FROM actividades_ministerio));

-- Automatic role synchronization:
-- Admin (1) is never changed.
-- Active membership => Miembro (3).
-- No active memberships => Usuario (2).
CREATE OR REPLACE FUNCTION fn_sincronizar_rol_miembro()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_id_usuario integer;
BEGIN
    v_id_usuario := COALESCE(NEW.id_usuario, OLD.id_usuario);

    IF EXISTS (
        SELECT 1
        FROM usuario
        WHERE id_usuario = v_id_usuario
          AND id_rol = 1
    ) THEN
        RETURN COALESCE(NEW, OLD);
    END IF;

    IF EXISTS (
        SELECT 1
        FROM usuarios_ministerio um
        WHERE um.id_usuario = v_id_usuario
          AND COALESCE(um.estado, 'Activo') = 'Activo'
          AND um.fecha_salida IS NULL
    ) THEN
        UPDATE usuario SET id_rol = 3 WHERE id_usuario = v_id_usuario;
    ELSE
        UPDATE usuario SET id_rol = 2 WHERE id_usuario = v_id_usuario;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER trg_sincronizar_rol_miembro
AFTER INSERT OR UPDATE OR DELETE ON usuarios_ministerio
FOR EACH ROW
EXECUTE FUNCTION fn_sincronizar_rol_miembro();

COMMIT;
